language: python
sudo: required

python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt

script: python manage.py test

deploy:
  ## Deploy to PYPI Test
  - provider: pypi
    user: "mensaah"
    password: $PYPI_PASSWORD
    on:
      tags: true
    skip_existing: true
    server: https://test.pypi.org/legacy/
#  - provider: heroku
#    install: skip
#    api_key: $HEROKU_PRODUCTION_API_KEY
#    app: $HEROKU_APP_NAME
