language: python

python:
  - "3.6"
  - "3.7"

services:
  - postgresql

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: test
      name: "Tests"
      before_script: psql -c 'create database travis_ci_test;' -U postgres
      script: python manage.py test --settings pipeline.settings.travis

    - stage: deploy
      name: "Deploy to PyPi"
      script: skip
      deploy: &pypi
        provider: pypi
        user: "mensaah"
        password: $PYPI_PASSWORD
        on:
          tags: true
        skip_existing: true
    
    - stage: deploy
      name: "Deploy to Heroku"
      script: skip
      deploy: &heroku
        provider: heroku
        on:
          tags: true
        install: skip
        api_key: $HEROKU_PRODUCTION_API_KEY
        app: $HEROKU_APP_NAME

    - stage: deploy
      name: "Deploy to GitHub Pages"
      script: cd docs && make html
      deploy: &pages
        provider: pages
        local_dir: docs/build/html
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: master
          tags: true

