language: python

python:
  - "3.6"
  - "3.7"

services:
  - postgresql

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: test
      name: "Tests"
      before_script: psql -c 'create database travis_ci_test;' -U postgres
      script: python manage.py test --settings pipeline.settings.travis

