language: python
sudo: required

python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt

script: cd pipeline && python manage.py test

## Deploy to PYPI
#deploy:
#  provider: pypi
#  user: "deven96"
#  password: $PYPI_PASSWORD
#  on:
#    tags: true
#  skip_existing: true
